---
seed: 100
model:
  active: ['caption']
  caption:
    hf_model: 
      name: google/bigbird-pegasus-large-pubmed #770 m parameters
torch_dist:
  use: true
  deepspeed: true  
train:
  intervals:
    eval: 100000