---
seed: 1
model:
  active: ['chart_text']
  chart_text_data:
    hf_model: 
      name: google/pegasus-pubmed #770 m parameters
data:
  dataset:
    chart_data:
      chart_text_output: ['series'] #,'series','axis', 'categorical'
torch_dist:
  use: true
  deepspeed: true  
train:
  intervals:
    eval: 100000