---
seed: 1
model:
  active: ['chart_text']
  chart_text_data:
    hf_model: 
      name: google/t5-v1_1-large #770 m parameters
data:
  dataset:
    chart_data:
      chart_text_output: ['categorical'] #,'series','axis', 'categorical'
torch_dist:
  use: true
  deepspeed: true  
train:
  intervals:
    eval: 100000
  gradient_accum_steps: 2
batch_size_per_gpu: 
  chart_text: 8